Add missing includes and consts for member functions
NaokiTakahashi12/cybergear_ros2 pull request #18
Opened 2024-11-23 21:49 UTC by Darkproduct

Some small things I found while working on my other PR.

One think I was also wondering about. Why are all members of `CybergearPacket` unique pointers?

https://github.com/NaokiTakahashi12/cybergear_ros2/blob/6af966674a414064089e343e69bf5d90a51a90ce/cybergear_driver_core/include/cybergear_driver_core/cybergear_packet.hpp#L224-L231

I mean, why not doing everything on the stack here?

2024-11-24 04:40 UTC, NaokiTakahashi12 commented
Thank you for the PR regarding performance improvements.

I believe the use of smart pointers for class members is unnecessary, as the current implementation only degrades performance.
While there might have been a reason for this choice during the initial implementation, I can no longer remember what it was.

2024-11-24 04:53 UTC, NaokiTakahashi12 requested changes
@Darkproduct 

In C++11 and later, it seems that cstdint should be used instead of stdint.h.
Could you update the header changes accordingly?

2024-11-24 04:53 UTC, NaokiTakahashi12 commented on cybergear_driver_core/include/cybergear_driver_core/protocol_constant.hpp
This header assumes C++ rather than C, so please use cstdint.

2024-11-24 04:53 UTC, NaokiTakahashi12 commented on cybergear_driver_core/include/cybergear_driver_core/bounded_float_byte_converter.hpp
This header assumes C++ rather than C, so please use cstdint.

2024-11-24 12:55 UTC, Darkproduct commented on cybergear_driver_core/include/cybergear_driver_core/protocol_constant.hpp
done

2024-11-24 12:55 UTC, Darkproduct commented on cybergear_driver_core/include/cybergear_driver_core/bounded_float_byte_converter.hpp
done

2024-11-24 12:57 UTC, Darkproduct commented
> Thank you for the PR regarding performance improvements.
> 
> I believe the use of smart pointers for class members is unnecessary, as the current implementation only degrades performance. While there might have been a reason for this choice during the initial implementation, I can no longer remember what it was.

Ok, then maybe will have a closer look in the future at this

2024-11-24 13:49 UTC, Darkproduct commented
> Ok, then maybe will have a closer look in the future at this

Done. I remove the unique pointers in 55d291f.

2024-11-24 14:11 UTC, Darkproduct commented
I think I've done everything (and a bit more) from what I wanted to do in this PR.

2024-11-25 03:53 UTC, NaokiTakahashi12 approved these changes

2024-11-25 03:54 UTC, merged